language: python

python:
  - "3.7"

os:
  - linux
  - osx

matrix:
  allow_failures:
    # Turns out OSX is "unsupported for Python github: travis-ci/travis-ci#2312"
    - os: osx

services:
  - mongodb
  - postgresql

before_script:
  - python setup develop
  - pip install pylint pytest

install:
  - python setup.py install
  
script:
  - pylint tgt_grease
  - python setup.py test
# Run twice to ensure state management is successful
  - python setup.py test
  - grease bridge register --foreground
  - grease help
  - grease daemon run --loop:5 --foreground
  - grease scan --loop:5 --foreground
  - grease detect --loop:5 --foreground
  - grease schedule --loop:5 --foreground
  - grease monitor --loop:5 --foreground
  - grease bridge assign --prototype:scan
  - grease bridge assign --prototype:detect
  - grease bridge assign --prototype:schedule
  - grease bridge info --jobs --pJobs
  - grease bridge unassign --prototype:scan
  - grease bridge unassign --prototype:detect
  - grease bridge unassign --prototype:schedule
  - grease bridge cull

deploy:
  on:
    branch: master
  provider: pypi
  user: $PYPI_USER
  password: 
    secure: $PYPI_PASSWORD
